PORT = 8000
MAX_NUMBER_OF_RESULTS = 30

EBAY_APP_ID_SANDBOX = "XXXXXXXXXXXXX"
EBAY_DOMAIN_SANDBOX = "open.api.sandbox.ebay.com"

EBAY_DOMAIN_PROD = "open.api.ebay.com"
EBAY_APP_ID_PROD = "XXXXXXXXXXXXXXx"

AMZ_ACCESS_KEY = "XXXXXXXXXXXXXXXX"
AMZ_SECRET_KEY = "XXXXXXXXXXXXXXXXXX"
AMZ_ASSOCIATE_TAG = "XXXXXXXXXXXXXX"

CACHE_TIMEOUT_MINUTES = 720
